language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get -y install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
  - npm install
script:
  - npm run build
  - ansible --version
#  - npm run test
# deploy:
#   provider: script
#   script: cd etc/ansible && ansible-playbook deploy.yml
#  on:
#    branch: master